### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by shulhi** [bcalik/Whatsapp-Desktop#11]
Anyone had the same problem? Just white screen, nothing is loaded into the screen.
<img width="862" alt="screen shot 2015-08-27 at 9 29 50 am" src="https://cloud.githubusercontent.com/assets/913103/9510443/40f935b4-4c9e-11e5-8b7e-2be98ddd0878.png">

**Comment by mariovillani** [comment]
I had this yesterday. I also noticed other errors. I'll try to fix them and do a pull request. However, Whatsapp Web was offline.
