### ISSUE TITLE
Disable menu item

### ISSUE THREAD

**Issue by ghost** [bcalik/Whatsapp-Desktop#13]
Hi is possible to disable menubar icon?

Thanks

**Comment by shulhi** [comment]
@cybermaster69 You would have to comment out these following line in `app.js`

```
  appIcon = new Tray(__dirname+'/assets/trayTemplate.png');
  appIcon.on("clicked", function(){
    win.show();
  });
  appIcon.setToolTip('WhatsApp');
```

I thought of making some sort of preferences panel when I have time.
