### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by zenkinz** [bcalik/Whatsapp-Desktop#15]
![capture](https://cloud.githubusercontent.com/assets/460511/10238656/45b9eaa8-68f5-11e5-86ee-9bc8f33def42.JPG)

run the whatapp executable binary after I unzip, and I get this error message. I could still proceed though.

**Comment by Dimbadboy** [comment]
Same here.

**Comment by bcalik** [comment]
@zenkinz @Dimbadboy 
This is probably fixed in latest release v0.3.0
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.0

Please check and tell me the result.

**Comment by Dimbadboy** [comment]
Not exactly. Now I get errors only when I click "WhatsApp Desktop", "Edit", "View" and "Window". Everything else seems to work properly. Also I found some bugs:

1)When the application is already running clicking the WhatsApp icon will lead to opening a second Window instead reopening the old one.

2) When I click "X" the WhatsApp window is closing but the icon in the tray box in the task bar is still there. On click it gets again javascript error.

Also I would like to give you an idea that for me it will be a better option. When you press "X" instead closing the app to go to the tray menu and work in a background. For example many other chat apps - Viber, Skype and etc.

**Comment by francwalter** [comment]
Windows 8.1 (64-Bit), version 0.3.0:
The "About WhatsApp" Menu entry gives me this:
![whatsapp-bcalik](https://cloud.githubusercontent.com/assets/927269/11091620/8f923170-887c-11e5-883e-4040889ad5ea.jpg)
And closing (Menu: quit) doesn't close the app and gives me again the same error.

Seems a bit buggy on Windows in version 0.3.0 
Can it be fixed?

**Comment by francwalter** [comment]
I guess this App is just not ready for Windows? I use on Windows now the other app "WOW", called WhatsApp On Windows. Works without bugs since.

**Comment by ghost** [comment]
I'm running Windows 10 x64 and experiencing the same issue. More than happy to carry out any trouble shooting.

**Comment by francwalter** [comment]
This app seems abandoned for Windows unfortunately :(

**Comment by ghost** [comment]
OH REALLY!! This is bar far the cleanest app.

Would be great if the notifications worked too. Hope this project continues. :-)

**Comment by bcalik** [comment]
Sorry I am not a Windows user, so I can not see how it works on Windows.
Anyone can contribute and fix it for me.

**Comment by ghost** [comment]
No worries. Just wish WhatsApp would bring out a fully integrated desktop client, like other instant messaging services.

**Comment by bcalik** [comment]
Could you please test the latest version:
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2
