### ISSUE TITLE
The App screen is blank from start.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [bcalik/Whatsapp-Desktop#17]
Running the latest release on OS X 10.11.1.
![screen shot 2015-10-30 at 4 59 54 pm](https://cloud.githubusercontent.com/assets/6371303/10844709/ca85eaf0-7f27-11e5-8493-bd385f06d882.png)

Deleted
`~/Library/Preferences/com.electron.whatsapp.plist` (not sure of the name of the file here now, since i've already deleted the file).
and
`~/Library/Application\ Support/whatsapp`

But, still the issue remains.

**Comment by bcalik** [comment]
Does http://web.whatsapp.com work for you?

**Comment by arjunmayilvaganan** [comment]
@bcalik , that was the first thing I checked and it worked. However, that browser was connected via VPN using a browser extension. After you've specifically asked, I incidentally tried without the extension enabled and http://web.whatsapp.com didn't seem to work. Must be some network issue in my location or Network config issue on my Computer. Sorry. And Thanks for responding. Now closing this issue.
