### ISSUE TITLE
Security: executing external malicious node.js code

### ISSUE THREAD

**Issue by Roboe** [bcalik/Whatsapp-Desktop#19]
Hi, there. I may say that my reasoning could be wrong, I've not checked it, but I think there could be an invisible [privilege escalation](https://en.wikipedia.org/wiki/Privilege_escalation) security issue with this Electron app.
This could be caused with third-party remote JS code, like WhatsApp code or any CDN libraries **without** the user notice.

Basically, the app fetches some unknown JS code and execute it in the node.js runtime instead of a normal browser JS runtime (Spidermonkey, V8), meaning that it has access to node.js IO (filesystem) and other potentially risky modules.

The solution may consist in execute the webpage in some kind of isolated sandbox, from which the JS code can't have any access to node.js capabilities.

Any real implementation for this? First step may be check Electron configs or some npm modules.

**Comment by bcalik** [comment]
Node integration feature is already disabled in this app. Also all the js libraries included are open sourced and trusted by the world. There shouldn't be any issue.

**Comment by Roboe** [comment]
Didn't read Electron docs, sorry. I just checked `browser-window` options.

Happy to read that! Keep up the good work, :+1:
