### ISSUE TITLE
can't run your client anymore. " We recommend using WhatsApp Web with one of the following browsers" 

### ISSUE THREAD

**Issue by olbapnauj** [bcalik/Whatsapp-Desktop#2]
Hello there, i was using your Desktop client on mac but today  i got the " We recommend using WhatsApp Web with one of the following browsers:  bla bla " tried download again but the problem persist. now i can't login or pass that error.  i don't have this problem on the aluxian version but is  not power friendly  like yours. 

http://prntscr.com/7vjccg

**Comment by bcalik** [comment]
Looks like it will not be easy to fix. I will investigate.

**Comment by tszming** [comment]
I am using another client "Unofficial WhatsApp" also start to have issue this morning, look like they have blocked it.

**Comment by olbapnauj** [comment]
some guys from the "Unoficial whatsapp github" posted that clearing the cache would fix the problem
"clear the whatsapp folder in ~/Library/ApplicationSupport,"  if you are using the mac version.

yup, im using the client again after clearing the cache folder you need to login again and thats it.

**Comment by bcalik** [comment]
@olbapnauj I've just tried, It really works interestingly. Thanks.
I will try to add a feature that automaticly clears the cache if the "browser not supported" screen appears.

**Comment by bcalik** [comment]
@olbapnauj Ok I released an update.

It now clears "~/Library/ApplicationSupport/Application Cache/Index" file automaticly. Not the entire ApplicationSupport folder. Thats enough. So it also keeps you logged-in.

**Comment by bcalik** [comment]
@olbapnauj The latest release was wrong. I just re-uploaded the zip file. Please download if it did not work for you.

**Comment by olbapnauj** [comment]
tbh i was using it without problems but i will update to the last version.

tyvm.
