### ISSUE TITLE
App not closing right on Windows

### ISSUE THREAD

**Issue by Jamushroom** [bcalik/Whatsapp-Desktop#20]
Been using this app for 2 days and I've noticed that it doesn't close the way it should. Electron keeps running in the background and the systemtray icon doesn't go away either. Launching another session of the app doesn't fix this, it just add another instance of Electron to the running processes and adds another systemtray icon.

Edit: I've noticed that the app launches 2 instances of Electron to begin with.

**Comment by bcalik** [comment]
Could you please test the latest version:
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2
