### ISSUE TITLE
A click on the notification should maximize the chat window (Mac)

### ISSUE THREAD

**Issue by FelixB91** [bcalik/Whatsapp-Desktop#22]
I noticed that when I close or minimize the window into the dock, a notification still appears and when I click on it, it´ll will also bring me to the main desktop, but it won´t maximize the window. 
It´s not critical, but it requires an additional action which can be a little bit annoying when you use it a lot (which I do right now).

**Comment by bcalik** [comment]
What do you mean by maximizing? When I click to the notification, it opens the app. Nothing is wrong here. Why should it maximize to fullscreen?

**Comment by FelixB91** [comment]
I´m sorry, maximize was definitly the wrong word here! 
I mean it doesn´t open the window from the dock. So if i minimize or close the window to the dock and click on a notification, it´ll navigate me to the main desktop page (if I´m in another space at that time), but won´t open the app.

**Comment by bcalik** [comment]
Try hiding the app (cmd+h) instead of minimizing. It will work for now.
I will try to find a solution to this.
