### ISSUE TITLE
Mac ⌘ + Ctrl + Space for Emojis does not work for me

### ISSUE THREAD

**Issue by AlexanderNeumann** [bcalik/Whatsapp-Desktop#23]
When I try to use the keyboard combination nothing happens :/

**Comment by bcalik** [comment]
Works for me. Maybe its about your osx configuration, i don't know.
Does it work on http://web.whatsapp.com for you? 

![screen shot 2016-02-26 at 00 41 37](https://cloud.githubusercontent.com/assets/9222368/13337008/c35848ac-dc21-11e5-9410-b50a5b0e6d04.png)

**Comment by AlexanderNeumann** [comment]
It works on http://web.whatsapp.com for me. In Version v0.2.1 everything worked fine. Yesterday I downloaded the newest version (v0.3.0) and nothing happens. Now I downloaded v0.21 again, where it is still working.

**Comment by bcalik** [comment]
Could you please test the latest version @AlexanderNeumann:
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2

**Comment by AlexanderNeumann** [comment]
Works with the current version. Great thanks 👍
