### ISSUE TITLE
Mac - clarifying all keyboard shortcuts?

### ISSUE THREAD

**Issue by jasonpaez** [bcalik/Whatsapp-Desktop#28]
Unclear that keyboard shortcuts like command+f exist (other than from release notes). Worth adding to the Edit menu, along with any other undocumented shortcuts?

Other nice keyboard shortcuts used by BetterChat on the app store are command+n for new messages, shift+command+n for new audio messages, and command+g for new group.

Those small changes along with the bug in search would make this best-in-class I believe.

**Comment by bcalik** [comment]
There isn't any other shortcut, but It would be great to have some.
I will try to add when I have some free time. Since then, pull requests are welcome :)
