### ISSUE TITLE
Send Image Console Browser

### ISSUE THREAD

**Issue by andrecordeiro** [bcalik/Whatsapp-Desktop#29]
Hello personal , all right?
I'm trying to accomplish sending images by browser cosole and I'm CORS (Cross Domain) problems. Does anyone know how I can do this ?

The following sample code:

var imageURL ="http://www.mydomain.com/image.jpg";
var canvas = document.createElement('canvas');
var context = canvas.getContext('2d');
var image = new Image();
image.setAttribute('crossorigin', 'anonymous');
image.onload = function () {
    canvas.width = image.width;
    canvas.height = image.height;
    context.drawImage(image, 0, 0, image.width, image.height);
    canvas.width(function (blob) {
        var event = new Event('drop');
        var uri = new URI(imageURL);
        var file = new File([blob], 'upload.' + uri.path.substr(uri.path.lastIndexOf('.') + 1), {type: 'image/' + (uri.path.substr(uri.path.lastIndexOf('.') + 1))});

```
});
```

};
image.src = imageURL;

Best regards .

**Comment by bcalik** [comment]
How is this related to the Whatsapp Desktop app?

**Comment by andrecordeiro** [comment]
yes
