### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by orschiro** [bcalik/Whatsapp-Desktop#3]
Hi @bcalik,

I am not sure whether you have seen my [comment](https://github.com/Aluxian/WhatsApp-Desktop/issues/42#issuecomment-125480300). 

Do you plan on releasing an Ubuntu deb package for your version? 

Is there any way I can help you with that?

Thankfully,

Robert

**Comment by thopiekar** [comment]
:+1:

**Comment by bcalik** [comment]
Could you please test the latest version on Linux.
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.2
