### ISSUE TITLE
Tray icon doesn't restore app's window

### ISSUE THREAD

**Issue by sharkile** [bcalik/Whatsapp-Desktop#30]
If you're using the app and close it's window it goes to the system's tray as shown here:

![screenshot from 2016-05-07 21-29-35](https://cloud.githubusercontent.com/assets/17736615/15095859/1af7c8c4-149b-11e6-9538-551df66ebcae.png)

But if you click on the icon instead of restoring the app's window you get this error:

![screenshot from 2016-05-07 21-30-20](https://cloud.githubusercontent.com/assets/17736615/15095860/314ed6ee-149b-11e6-8a36-224b7ce2dca8.png)

And the process is still shown as running:

![screenshot from 2016-05-07 21-36-14](https://cloud.githubusercontent.com/assets/17736615/15095866/cde7c1dc-149b-11e6-97cb-9ce5e9542707.png)

I'm running Debian testing x64 with GNOME.

**Comment by shyamsathyanathan** [comment]
I'm facing the same issue on Ubuntu 16.04 with GNOME shell. Any updates on this?

**Comment by bcalik** [comment]
@championswimmer added linux support, he may know.
@bil-elmoussaoui may also know.

I have never tried on linux.

**Comment by championswimmer** [comment]
I'll take a look. Have not checked with GNOME shell ever.

**Comment by shyamsathyanathan** [comment]
Hmm. Does this mean this works as expected on Unity?

**Comment by championswimmer** [comment]
Unity does not have a tray like the one introduced in GNOME 3.18

**Comment by championswimmer** [comment]
I've been sorta AWOL from the electron scene, don't know if Electron
supports the new GNOME shell tray properly or not.

**Comment by andreluizmg** [comment]
Here in KDE same thing spite this annoying bug awesome app!
![screenshot_20170323_163849](https://cloud.githubusercontent.com/assets/26634756/24266948/632447d8-0fe7-11e7-8666-ae4be86f4e6c.png)

**Comment by wotomg** [comment]
Same problem in Xfce.

**Comment by MartinX3** [comment]
Linux Mint 18.1 x64 Mate-Edition 
Based on Ubuntu 16.04

Same Error
> Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at Tray.whatsApp.tray.on (/home/martin/Desktop/WhatsApp-linux-x64/resources/app/main.js:131:33)
    at emitTwo (events.js:87:13)
    at Tray.emit (events.js:172:7)
    at Tray.<anonymous> (/home/martin/Desktop/WhatsApp-linux-x64/resources/atom.asar/common/api/deprecate.js:74:26)
    at emitTwo (events.js:87:13)
    at Tray.emit (events.js:172:7)

**Comment by rawzone** [comment]
Also same problem on [i3wm](https://i3wm.org).

Would also be nice to have an option to toggle to a inverted icon (White / Black).

**Comment by championswimmer** [comment]
Problem here is I have moved to Mac
I'll try to run my old Linux laptop someday soon, and when I do, this is
the first thing I'll try to solve :)

**Comment by rawzone** [comment]
Added a pull request with a workaround for the tray icon not working under Linux - See #40 for more information.
