### ISSUE TITLE
What's the license of the project?

### ISSUE THREAD

**Issue by bilelmoussaoui** [bcalik/Whatsapp-Desktop#35]
The license is needed in order to get the packaging done on some linux distro... I assume it's MIT?
also if you can add the license on  github it would be better :)

**Comment by bcalik** [comment]
Do whatever you want @bil-elmoussaoui

**Comment by bilelmoussaoui** [comment]
Well, i created a package for ArchLinux users here https://aur.archlinux.org/packages/whatsapp-desktop/ and i used MIT as a license ;)
