### ISSUE TITLE
Windows binaries?

### ISSUE THREAD

**Issue by omperus** [bcalik/Whatsapp-Desktop#4]
Is it possible to get windows binaries?

**Comment by bcalik** [comment]
Ok then. I will do some testing on Windows today, then I will release a new version if nothing is wrong.

**Comment by bcalik** [comment]
@omperus Could you please try it?
https://github.com/bcalik/Whatsapp-Desktop/releases/download/v0.1.5/Whatsapp-win32-x64.zip

I am not a Windows user, so I don't know your needs.
Please try it and tell me your requests.

**Comment by bcalik** [comment]
@omperus Have you tried?

**Comment by francwalter** [comment]
I tried it just. It seems to work initially but when I do the Menu:
**WhatsApp / Hide WhatsApp**
I get an error:
A JavaScript error occured in the browser process:

![wa-error-js](https://cloud.githubusercontent.com/assets/927269/9085577/47dd9dd8-3b7e-11e5-8406-29a471030853.jpg)

What is elseway inconvenient is that the close button does close totally, it is not possible to put the app on close only in the system tray like the other app Inofficial WhatsApp can do it.
I would need further applications to do this job (e.g. AutoHotKey's Min2Tray etc.)

Possible to fix?

**Comment by francwalter** [comment]
On work or abandoned here also?

**Comment by bcalik** [comment]
I couldn't find free time last week to work on this. @francwalter 
I hope I will work this week.

**Comment by francwalter** [comment]
Tell me if you need test.

**Comment by bcalik** [comment]
https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.0
