### ISSUE TITLE
The Icon in the System Tray doesnt go away.

### ISSUE THREAD

**Issue by samsumas** [bcalik/Whatsapp-Desktop#41]
Good Evening,
After Closing Whatsapp-Desktop, the Icon in the System Tray doesnt go away. When I click on it it says : 
![image](https://cloud.githubusercontent.com/assets/13918999/24873964/337ad340-1e23-11e7-9110-cf2ea0cbad57.png)
Wanted behavior: make the thing disappear after closing Whatsapp-Desktop.
After opening and closing n times Whatsapp-Desktop i have n Icons spamming my System Tray.
![image](https://cloud.githubusercontent.com/assets/13918999/24874261/5a5553cc-1e24-11e7-8512-fad87b76ceca.png)
OS: ArchLinux (64bit) with kde-plasma, Whatsapp-Desktop downloaded from the AUR with pkgbuilder

**Comment by rawzone** [comment]
@samsumas please try git clone the repo as it seems like the Arch package maintainer haven't updated - Some time back i supplied a[ "patch"](https://github.com/bcalik/Whatsapp-Desktop/pull/40) that reworked the trayicon for linux.

**Comment by rawzone** [comment]
@samsumas Did you try the master branch? Is there any errors that should be fixed on this account?
Its currently working very well in my setup?

**Comment by MartinX3** [comment]
Yes, same Problem at my side
Running the last release from 06.04.2016 on Linux.

**Comment by rawzone** [comment]
@MartinX3 Please try to clone the master branch as the rewrite of the Linux tray stuff seems not to have been tagged in a release yet.

**Comment by samsumas** [comment]
Nice the master works properly!!!

**Comment by MartinX3** [comment]
@rawzone
You mean, I need to compile it on my own?
