### ISSUE TITLE
Project still alive? New Release?

### ISSUE THREAD

**Issue by MartinX3** [bcalik/Whatsapp-Desktop#42]
Is this Project still alive?
The last release is  from 6 Apr 2016 and and there happen 21  commits to master since this release.

**Comment by bcalik** [comment]
No because whatsapp released their official app.

**Comment by MartinX3** [comment]
I see no official Linux Debian Ubuntu Mint APP.
Could you give me the Link?

**Comment by bcalik** [comment]
This one does not support Linux too. Quote from readme file:
`Firsty, please note that Linux version is not tested and it's probably buggy.`

**Comment by MartinX3** [comment]
Could you provide a new Linux Build again, like you already did in 2016?

**Comment by bcalik** [comment]
I'm not a linux user, so I did not provide a linux build, maybe you could ask @championswimmer or @bil-elmoussaoui to do. Or you can contribute too, like what they did.

**Comment by bcalik** [comment]
@MartinX3 try this: https://github.com/bcalik/Whatsapp-Desktop/releases/tag/v0.3.3

**Comment by MartinX3** [comment]
THANK YOU VERY MUCH!
