### ISSUE TITLE
demo screenshot

### ISSUE THREAD

**Issue by roccomuso** [bcalik/Whatsapp-Desktop#48]
It would be nice to have a screenshot of the app in the README.md.

**Comment by bcalik** [comment]
Its just a desktop client of web version of whatsapp. There is nothing visually different.

**Comment by roccomuso** [comment]
So what's the different compared to https://github.com/jiahaog/nativefier ?

**Comment by bcalik** [comment]
I don't know what it is. I've just made this for myself.
