### ISSUE TITLE
change applet icon

### ISSUE THREAD

**Issue by rotsix** [bcalik/Whatsapp-Desktop#50]
Hi guys!

How can I change the applet icon ? Does it depend on the gtk-icon-theme ?
https://ptpb.pw/X7ij.png

Regards,
rotsix

**Comment by Enrico204** [comment]
Hi @rotsix , all icons are bundled with the app, by now there is no way to change that at runtime. You'll need to download the source code and recompile the app.

**Comment by rotsix** [comment]
Icon isn't set using the Gtk icon theme ?
Thank you

**Comment by rotsix** [comment]
Ow OK, [hard-coded](https://github.com/bcalik/Whatsapp-Desktop/blob/master/app/assets/img/trayTemplate.png)
So, improvement idea: let the gtk icon theme manage the applet icon haha.

Regards,
rotsix

**Comment by Enrico204** [comment]
@ceyhunnabiyev @bil-elmoussaoui Due to #42 and the fact that @bcalik has no more time to dedicate to this project, I'll continue on my fork: https://github.com/Enrico204/Whatsapp-Desktop
