### ISSUE TITLE
How to get customize dialog box instead of app notification for any new message

### ISSUE THREAD

**Issue by garg-ashu** [bcalik/Whatsapp-Desktop#54]
I want to get customize dialog box with new message and contact details of that person instead of standard notification.
Can i do that? If Yes..Please guide me how to do it?

**Comment by Enrico204** [comment]
Hi @garg-ashu , I just took over the development of this project, the repository now is at https://github.com/Enrico204/Whatsapp-Desktop , please open this issue there ;-)
Thanks ;-)
