### ISSUE TITLE
Weird screen

### ISSUE THREAD

**Issue by antonkulaga** [bcalik/Whatsapp-Desktop#56]
That is what I see when I try to login

![bug_whatsapp](https://user-images.githubusercontent.com/842436/27544586-482cb934-5a96-11e7-9e1c-638034395153.png)

**Comment by bcalik** [comment]
It is what you are supposed to see. What is the problem?

**Comment by antonkulaga** [comment]
My mistake. I had to add whatsup today to keep in touch with some people in our lab and I did not expect that its hello screen is so confusing
