### ISSUE TITLE
Whatsapp app shows the desktop as Mac Version

### ISSUE THREAD

**Issue by oscarr-reyes** [bcalik/Whatsapp-Desktop#58]
I have found out that this wrapper was done using `electron` wrapper, and after checking the connections my `whatsapp` has i have seen that the application shows the desktop connection as if it was connected using the `Mac` version while using the original web version shows the correct OS name which in my case is `Debian Ubuntu`

**Comment by Enrico204** [comment]
Hi @oscarr-reyes , this issue is fixed into the new repo. The development was moved here: https://github.com/Enrico204/Whatsapp-Desktop
